name: docker-build

on:
  push:
    branches: ["main"]
env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: jamescarnegie559/test-docker-image
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
  DOCKERFILE_PATH: Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SHA }}

      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a #v4.0.1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=jonnystoten2/buildkit:kms-signing
            env.AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
            env.AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
            env.AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }}
            env.AWS_REGION=${{ vars.AWS_REGION }}

      - name: Log into registry
        if: ${{ github.event_name == 'push' || github.event.inputs.push }}
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image on push
        id: build-and-push
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: "linux/amd64"
          sbom: true
          provenance: true
